// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Indigo",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Indigo",
            targets: ["AppModule"],
            bundleIdentifier: "andama.Indigo",
            teamIdentifier: "9546RNY8GD",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Resources/IndigoLeafClassifier.mlmodel"],
            resources: [
                .process("Assets.xcassets"),
                .copy("Resources/IndigoLeafClassifier.mlmodelc"),
                .process("Resources/healthy_1.jpg"),
                .process("Resources/healthy_2.jpg"),
                .process("Resources/healthy_3.jpg"),
                .process("Resources/rust_1.jpg"),
                .process("Resources/rust_2.jpg"),
                .process("Resources/rust_3.jpg")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
